name: CI

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        values: [
          {docker_tag: "v1.0", prefix: "iop", flag: "l"},
          {docker_tag: "v1.1", prefix: "iop", flag: "l"},
          {docker_tag: "v1.2.0", prefix: "iop", flag: "l"}, 
          {docker_tag: "latest", prefix: "mipsel-ps2-irx", flag: "l"}, 
        ]

    container: ps2dev/ps2dev:${{ matrix.values.docker_tag }}
    
    - name: Check headers
      run: |
        cd $PS2DEV/ps2sdk/iop/irx
        ${{ matrix.values.prefix }}-readelf -${{ matrix.values.flag }} audsrv.irx

    - name: Binutils version
      run: |
        ${{ matrix.values.prefix }}-readelf --version

